### ISSUE TITLE
Support Asset type “Code:IssuerAccountID”

### ISSUE THREAD

**Issue by ejorritsma** [Baseflow/stellar-rust-sdk#16]
Right now in the AccountsRequest struct there is a filter for `asset` which now consists of the enum `AssetType`.

The `AssetType` has currently two possible values: `Native` and `Issued`. 

 Issued, should have the following values.
* Asset Code
* Issuer Account ID

See also:
* https://laboratory.stellar.org/#explorer?resource=accounts&endpoint=multiple&values=eyJhc3NldCI6IjoifQ%3D%3D&network=test 
* https://developers.stellar.org/api/horizon/resources/list-all-accounts

**Comment by pnehkan** [comment]
Fixed by merging this branch https://github.com/Baseflow/stellar-rust-sdk/pull/29

**Comment by ejorritsma** [comment]
Fixed by merging this branch https://github.com/Baseflow/stellar-rust-sdk/pull/29
