### ISSUE TITLE
Complete documentation (depracated issue)

### ISSUE THREAD

**Issue by LeonardTibben** [Baseflow/stellar-rust-sdk#4]

**Comment by ejorritsma** [comment]
It would help users of the Stellar Rust SDK if the documentation was complete

* Include (more) examples where relevant
* Cover everything the developer needs to know (so not private fields, but do document how to properly make an AllAccountsRequest etcetera)
* Make sure `cargo doc` produces nice output (for example, hiding all crates that we use internally from the documentation, having an intuitive way to click through the documentation)

**Comment by ejorritsma** [comment]
Comments moved here from https://github.com/Baseflow/stellar-rust-sdk/pull/12
by Thomas

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
    pub fn set_asset_issuer(&mut self, asset_issuer: &str) -> &mut Self {
        self.asset_issuer = Some(asset_issuer.to_owned());
        self
    pub fn set_asset_issuer(self, asset_issuer: &str) -> Result<AllAssetsRequest, String> {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404231201)

We should add the boundaries to the documentation, so the developers know if they mess up, why their code doesn't compile.

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
    pub fn set_asset_code(&mut self, asset_code: &str) -> &mut Self {
        self.asset_code = Some(asset_code.to_owned());
        self
    pub fn set_asset_code(self, asset_code: &str) -> Result<AllAssetsRequest, String> {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404231345)

We should add the boundaries to the documentation, so the developers know if they mess up, why their code doesn't compile.

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
    pub fn set_cursor(&mut self, cursor: u32) -> &mut Self {
        self.cursor = Some(cursor);
        self
    pub fn set_cursor(self, cursor: u32) -> Result<AllAssetsRequest, String> {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404232625)

We should add the boundaries to the documentation, so the developers know if they mess up, why their code doesn't compile.

***


[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
    pub fn set_limit(&mut self, limit: u32) -> &mut Self {
        self.limit = Some(limit);
        self
    pub fn set_limit(self, limit: u32) -> Result<AllAssetsRequest, String> {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404237509)

We should add the limit boundaries to the documentation, so developers know why their code no longer compiles if it does so.

***

[src/claimable_balances/all_claimable_balances_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-8d572f886df13907044f0e5f3f0605d18d2107d053c439c9f8609e336c72ab92)
Comment on lines 30 to +32
}

impl Request for AllClaimableBalancesRequest {

impl AllClaimableBalancesRequest {
Member
@[tluijken](https://github.com/tluijken) tluijken https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404242993

A lot of the comments from the all assets request also apply here. Don't forget to add boundaries to the documentation.

***

[src/claimable_balances/single_claimable_balance_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-5f0343fdc3a4d2906789253b56899ed40f0eefe732618d273300615f5c7ddcb0)
Comment on lines +12 to +19
pub struct SingleClaimableBalanceRequest<`I> {
    claimable_balance_id: I,
}

impl SingleClaimableBalanceRequest<NoClaimableBalanceId> {
    pub fn new() -> Self {
        SingleClaimableBalanceRequest::default()
    }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404244065)

We should add some documentation. It seems obvious, but that does this actually do?


***

[src/accounts/single_account_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-09ddcfb8a44c5c2197121b40b6429f6f93232718a710dc2a4d4771f7f246d5d6)
Comment on lines +3 to +6
#[derive(Default, Clone)]
pub struct AccountId(String);
#[derive(Default, Clone)]
pub struct NoAccountId;
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404244368)

We should add some documentation on the context of each of these states. What do they mean,?

***

[src/claimable_balances/single_claimable_balance_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-5f0343fdc3a4d2906789253b56899ed40f0eefe732618d273300615f5c7ddcb0)
Comment on lines +4 to +8
#[derive(Default, Clone)]
pub struct ClaimableBalanceId(String);
#[derive(Default, Clone)]
pub struct NoClaimableBalanceId;

Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404244641)

We should add some documentation on the context of each of these states. What do they mean?


***

[src/claimable_balances/single_claimable_balance_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-5f0343fdc3a4d2906789253b56899ed40f0eefe732618d273300615f5c7ddcb0)
        SingleClaimableBalanceRequest {
            claimable_balance_id: None,
impl<I> SingleClaimableBalanceRequest<I> {
    pub fn set_claimable_balance_id(
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404250561)

Please add some documentation on what this does, if there are any limitations on the input, and what the output will be.

***

[src/ledgers/ledgers_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-6f5476ef41b90a2c9b6f1f7cc303ed05183eb7227ed5ea976af7300acf575496)
Comment on lines +62 to +64
        if cursor < 1 {
            return Err("cursor must be greater than or equal to 1".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404258500)

The same remarks as earlier. 
Please update the docs indicating what the boundaries are for the cursor.

***

[src/ledgers/ledgers_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-6f5476ef41b90a2c9b6f1f7cc303ed05183eb7227ed5ea976af7300acf575496)
Comment on lines +81 to +84
    pub fn set_limit(self, limit: u32) -> Result<LedgersRequest, String> {
        if limit < 1 || limit > 200 {
            return Err("limit must be between 1 and 200".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404258864)

The same remarks as earlier.
Please update the docs indicating what the boundaries are for the cursor.
