### ISSUE TITLE
Consolidate Assets into a single location

### ISSUE THREAD

**Issue by kevin-pease** [Baseflow/stellar-rust-sdk#80]
Currently there are multiple instances of Assets declared in several requests throughout the codebase (for example, all trades request). It would be preferable to make it generally available (for example, in models).

It's important to note that there are different types of assets for requests:

One type contains extra data (i.e. `alphanumeric4`, `alphanumeric12` and `native`). Check the [Stellar Laboratory](https://laboratory.stellar.org/#explorer?resource=trades&endpoint=all&network=test) to see which parameters should be provided, and how the API request is formed.

The other type is somewhat similar, but takes different parameters. Check the [Stellar Laboratory](https://laboratory.stellar.org/#explorer?resource=claimable_balances&endpoint=multiple&values=eyJhc3NldCI6IiJ9&network=test) for an example.

There is already an `Asset` declared in models, this should be taken into consideration. Lastly, when making assets generally available in one location, the url building can also be moved to one location. See feedback on [pull request 71 ](https://github.com/Baseflow/stellar-rust-sdk/pull/71).

**Comment by tluijken** [comment]
Done together with Leonard on 10-9-2024 on develop branch.
