### ISSUE TITLE
AssetType struct in a Request Models module

### ISSUE THREAD

**Issue by LeonardTibben** [Baseflow/stellar-rust-sdk#98]
**Is your feature request related to a problem? Please describe.**
In different places an 'AssetType' is used as an type by requests, these are defined in the same way in different places, ie, code duplication. 

**Describe the solution you'd like**

A Requests Models module containing an AssetType enum and Asset. An AssetType Enum with native, alphanumcredit4 and alphanumcredit12 values, with the latter two containing an asset code and asset issuer.

**Describe alternatives you've considered**
Code duplication

**Comment by tluijken** [comment]
Implemented on develop branch together with @LeonardTibben
